# Generated by Django 5.2.9 on 2025-12-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_common60_idcode_alter_common61_idcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='see',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='See'),
        ),
    ]
