# Generated by Django 4.2.1 on 2023-07-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=120, unique=True, verbose_name='Username')),
                ('fullname', models.CharField(max_length=120, verbose_name='Full Name')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='Phone Number')),
                ('brithday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('idcode', models.BigIntegerField(blank=True, null=True, verbose_name='ID Code')),
                ('contery', models.CharField(blank=True, max_length=120, null=True, verbose_name='Contery')),
                ('sickness', models.CharField(blank=True, max_length=120, null=True, verbose_name='Sickness')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('reagent', models.BigIntegerField(blank=True, null=True, verbose_name='Reagent Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
