# Generated by Django 4.2.1 on 2023-07-06 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_name', models.CharField(max_length=120, verbose_name='help name')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pa', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
            ],
            options={
                'verbose_name': 'PublicAssistance',
                'verbose_name_plural': 'PublicAssistances',
            },
        ),
        migrations.CreateModel(
            name='JudiciaryDead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Deceased name')),
                ('idcode', models.IntegerField(verbose_name='Id Code')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery/State')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('phoneagent', models.IntegerField(verbose_name='Phone Number Agent')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jd', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
            ],
            options={
                'verbose_name': 'JudiciaryDead',
                'verbose_name_plural': 'JudiciaryDeads',
            },
        ),
        migrations.CreateModel(
            name='DoingDead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Deceased name')),
                ('idcode', models.IntegerField(verbose_name='Id Code')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery/State')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('phoneagent', models.IntegerField(verbose_name='Phone Number Agent')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dd', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
            ],
            options={
                'verbose_name': 'DoingDead',
                'verbose_name_plural': 'DoingDeads',
            },
        ),
        migrations.CreateModel(
            name='CommonDead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Deceased name')),
                ('idcode', models.IntegerField(verbose_name='Id Code')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery/State')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('phoneagent', models.IntegerField(verbose_name='Phone Number Agent')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cd', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
            ],
            options={
                'verbose_name': 'CommonDead',
                'verbose_name_plural': 'CommonDeads',
            },
        ),
        migrations.CreateModel(
            name='Common70',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Quadruple common name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('idcode', models.IntegerField(verbose_name='Id Code')),
                ('Sickness', models.CharField(max_length=120, verbose_name='sickness')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery/State')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('phoneagent', models.IntegerField(verbose_name='Phone Number Agent')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_c70', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
            ],
            options={
                'verbose_name': 'Common70',
                'verbose_name_plural': 'Common70s',
            },
        ),
        migrations.CreateModel(
            name='Common61',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Quadruple common name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('idcode', models.IntegerField(verbose_name='Id Code')),
                ('Sickness', models.CharField(max_length=120, verbose_name='sickness')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery/State')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('phoneagent', models.IntegerField(verbose_name='Phone Number Agent')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_c61', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
            ],
            options={
                'verbose_name': 'Common61',
                'verbose_name_plural': 'Common61s',
            },
        ),
        migrations.CreateModel(
            name='Common60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Quadruple common name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('idcode', models.IntegerField(verbose_name='Id Code')),
                ('Sickness', models.CharField(max_length=120, verbose_name='sickness')),
                ('contery', models.CharField(max_length=120, verbose_name='Contery/State')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('phoneagent', models.IntegerField(verbose_name='Phone Number Agent')),
                ('usersubmit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_c60', to=settings.AUTH_USER_MODEL, verbose_name='Registrant')),
            ],
            options={
                'verbose_name': 'Common60',
                'verbose_name_plural': 'Common60s',
            },
        ),
    ]
