# Generated by Django 4.2.1 on 2023-07-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='common60',
            old_name='Sickness',
            new_name='sickness',
        ),
    ]
