# Generated by Django 5.0.3 on 2024-06-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common60',
            name='contery',
            field=models.CharField(choices=[('Iraq', 'Iraq'), ('Iran', 'Iran'), ('Syria', 'Syria'), ('Sweden', 'Sweden'), ('Australia', 'Australia'), ('Denmark', 'Denmark'), ('Lebanon', 'Lebanon'), ('Saudi', 'Saudi'), ('Bahrain', 'Bahrain'), ('Kuwait', 'Kuwait'), ('Emirates', 'Emirates'), ('America', 'America'), ('India', 'India'), ('Pakistan', 'Pakistan'), ('Turkey', 'Turkey')], max_length=120, verbose_name='Contery'),
        ),
        migrations.AlterField(
            model_name='common61',
            name='contery',
            field=models.CharField(choices=[('Iraq', 'Iraq'), ('Iran', 'Iran'), ('Syria', 'Syria'), ('Sweden', 'Sweden'), ('Australia', 'Australia'), ('Denmark', 'Denmark'), ('Lebanon', 'Lebanon'), ('Saudi', 'Saudi'), ('Bahrain', 'Bahrain'), ('Kuwait', 'Kuwait'), ('Emirates', 'Emirates'), ('America', 'America'), ('India', 'India'), ('Pakistan', 'Pakistan'), ('Turkey', 'Turkey')], max_length=120, verbose_name='Contery'),
        ),
        migrations.AlterField(
            model_name='common70',
            name='contery',
            field=models.CharField(choices=[('Iraq', 'Iraq'), ('Iran', 'Iran'), ('Syria', 'Syria'), ('Sweden', 'Sweden'), ('Australia', 'Australia'), ('Denmark', 'Denmark'), ('Lebanon', 'Lebanon'), ('Saudi', 'Saudi'), ('Bahrain', 'Bahrain'), ('Kuwait', 'Kuwait'), ('Emirates', 'Emirates'), ('America', 'America'), ('India', 'India'), ('Pakistan', 'Pakistan'), ('Turkey', 'Turkey')], max_length=120, verbose_name='Contery'),
        ),
        migrations.AlterField(
            model_name='commondead',
            name='contery',
            field=models.CharField(choices=[('Iraq', 'Iraq'), ('Iran', 'Iran'), ('Syria', 'Syria'), ('Sweden', 'Sweden'), ('Australia', 'Australia'), ('Denmark', 'Denmark'), ('Lebanon', 'Lebanon'), ('Saudi', 'Saudi'), ('Bahrain', 'Bahrain'), ('Kuwait', 'Kuwait'), ('Emirates', 'Emirates'), ('America', 'America'), ('India', 'India'), ('Pakistan', 'Pakistan'), ('Turkey', 'Turkey')], max_length=120, verbose_name='Contery'),
        ),
        migrations.AlterField(
            model_name='doingdead',
            name='contery',
            field=models.CharField(choices=[('Iraq', 'Iraq'), ('Iran', 'Iran'), ('Syria', 'Syria'), ('Sweden', 'Sweden'), ('Australia', 'Australia'), ('Denmark', 'Denmark'), ('Lebanon', 'Lebanon'), ('Saudi', 'Saudi'), ('Bahrain', 'Bahrain'), ('Kuwait', 'Kuwait'), ('Emirates', 'Emirates'), ('America', 'America'), ('India', 'India'), ('Pakistan', 'Pakistan'), ('Turkey', 'Turkey')], max_length=120, verbose_name='Contery'),
        ),
        migrations.AlterField(
            model_name='judiciarydead',
            name='contery',
            field=models.CharField(choices=[('Iraq', 'Iraq'), ('Iran', 'Iran'), ('Syria', 'Syria'), ('Sweden', 'Sweden'), ('Australia', 'Australia'), ('Denmark', 'Denmark'), ('Lebanon', 'Lebanon'), ('Saudi', 'Saudi'), ('Bahrain', 'Bahrain'), ('Kuwait', 'Kuwait'), ('Emirates', 'Emirates'), ('America', 'America'), ('India', 'India'), ('Pakistan', 'Pakistan'), ('Turkey', 'Turkey')], max_length=120, verbose_name='Contery'),
        ),
    ]
