# Generated by Django 5.0.3 on 2024-11-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_common60_contery_alter_common61_contery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common60',
            name='age',
        ),
        migrations.RemoveField(
            model_name='common61',
            name='age',
        ),
        migrations.RemoveField(
            model_name='common70',
            name='age',
        ),
    ]
