# Generated by Django 5.0.3 on 2024-11-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_common60_age_remove_common61_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='common60',
            name='age',
            field=models.IntegerField(default=1994, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='common61',
            name='age',
            field=models.IntegerField(default=1994, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='common70',
            name='age',
            field=models.IntegerField(default=1994, verbose_name='Age'),
            preserve_default=False,
        ),
    ]
