# Generated by Django 5.0.3 on 2024-11-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_common60_age_common61_age_common70_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common60',
            name='idcode',
            field=models.PositiveBigIntegerField(verbose_name='Id Code'),
        ),
        migrations.AlterField(
            model_name='common61',
            name='idcode',
            field=models.PositiveBigIntegerField(verbose_name='Id Code'),
        ),
        migrations.AlterField(
            model_name='common70',
            name='idcode',
            field=models.PositiveBigIntegerField(verbose_name='Id Code'),
        ),
        migrations.AlterField(
            model_name='commondead',
            name='idcode',
            field=models.PositiveBigIntegerField(verbose_name='Id Code'),
        ),
        migrations.AlterField(
            model_name='judiciarydead',
            name='idcode',
            field=models.PositiveBigIntegerField(verbose_name='Id Code'),
        ),
    ]
