# Generated by Django 4.2 on 2023-07-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_publicassistance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicassistance',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
