# Generated by Django 4.2.1 on 2023-07-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_publicassistance_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='common61',
            old_name='Sickness',
            new_name='sickness',
        ),
        migrations.RenameField(
            model_name='common70',
            old_name='Sickness',
            new_name='sickness',
        ),
    ]
