# Generated by Django 4.2 on 2023-07-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_rename_sickness_common61_sickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='common60',
            name='city',
            field=models.CharField(default='none', max_length=120, verbose_name='State/City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='common61',
            name='city',
            field=models.CharField(default='n', max_length=120, verbose_name='State/City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='common70',
            name='city',
            field=models.CharField(default='n', max_length=120, verbose_name='State/City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commondead',
            name='city',
            field=models.CharField(default='n', max_length=120, verbose_name='State/City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doingdead',
            name='city',
            field=models.CharField(default='n', max_length=120, verbose_name='State/City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judiciarydead',
            name='city',
            field=models.CharField(default='n', max_length=120, verbose_name='State/City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='common60',
            name='contery',
            field=models.CharField(max_length=120, verbose_name='Contery'),
        ),
        migrations.AlterField(
            model_name='common61',
            name='contery',
            field=models.CharField(max_length=120, verbose_name='Contery'),
        ),
        migrations.AlterField(
            model_name='common70',
            name='contery',
            field=models.CharField(max_length=120, verbose_name='Contery'),
        ),
        migrations.AlterField(
            model_name='commondead',
            name='contery',
            field=models.CharField(max_length=120, verbose_name='Contery'),
        ),
        migrations.AlterField(
            model_name='doingdead',
            name='contery',
            field=models.CharField(max_length=120, verbose_name='Contery'),
        ),
        migrations.AlterField(
            model_name='judiciarydead',
            name='contery',
            field=models.CharField(max_length=120, verbose_name='Contery'),
        ),
    ]
