# Generated by Django 4.2 on 2023-07-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_common60_city_common61_city_common70_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('quran', 'Quran memorization lottery'), ('ziarat', 'Visiting religious places')], max_length=200, null=True, verbose_name='Lottery')),
            ],
            options={
                'verbose_name': 'Lottery',
                'verbose_name_plural': 'Lotterys',
            },
        ),
        migrations.AddField(
            model_name='common60',
            name='lottery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lottery', verbose_name=''),
        ),
    ]
