# Generated by Django 4.2 on 2023-07-30 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0011_alter_common60_lottery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('seedate', models.DateTimeField(auto_now=True, verbose_name='See Date')),
                ('subject', models.CharField(max_length=120, verbose_name='Subject')),
                ('text', models.TextField(verbose_name='Text')),
                ('see', models.BooleanField(default=False, verbose_name='See')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_msg', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
