# Generated by Django 4.2 on 2023-07-30 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0012_messagenotification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageNotification',
            new_name='Notification',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
