# Generated by Django 4.2.1 on 2023-08-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_winnerlottery60_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerlottery60',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='winnerlottery60',
            unique_together={('name', 'windate')},
        ),
    ]
