# Generated by Django 4.2.1 on 2023-08-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_winnerlottery60_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='winnerlottery60',
            unique_together=set(),
        ),
    ]
