# Generated by Django 4.2.1 on 2023-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_notification_see'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerlottery60',
            name='windate',
            field=models.DateTimeField(auto_now=True, verbose_name='Add Time'),
        ),
    ]
