# Generated by Django 4.2.1 on 2023-08-10 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0025_alter_winnerlottery60_windate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountGiftPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'AmountGiftPay',
                'verbose_name_plural': 'AmountGiftPays',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amountgiftpay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qst', to='crm.amountgiftpay', verbose_name='AmountGiftPay')),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
            },
        ),
        migrations.CreateModel(
            name='GiftTable24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Table Name')),
                ('monthnumber', models.IntegerField(verbose_name='Month Number')),
                ('amounttab1', models.FloatField(blank=True, null=True, verbose_name='Amount Tabale 1')),
                ('amounttab2', models.FloatField(blank=True, null=True, verbose_name='Amount Tabale 2')),
                ('amounttab3', models.FloatField(blank=True, null=True, verbose_name='Amount Tabale 3')),
                ('monthamount', models.FloatField(blank=True, null=True, verbose_name='Month Amount')),
                ('subtraction', models.FloatField(verbose_name='subtraction')),
                ('friendships', models.FloatField(verbose_name='Friendships and affections')),
                ('numberannual', models.FloatField(verbose_name='Annual number')),
                ('amountannual', models.FloatField(verbose_name='Annual Amount')),
                ('totalsubtraction', models.FloatField(verbose_name='Total Subtraction')),
                ('totalfriendships', models.FloatField(verbose_name='Total Friendships')),
                ('gifts', models.CharField(max_length=200, verbose_name='Gifts')),
                ('monthsequence', models.FloatField(verbose_name='monthsequence')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'GiftTable24',
                'verbose_name_plural': 'GiftTable24s',
            },
        ),
        migrations.AddField(
            model_name='amountgiftpay',
            name='gifttable',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giftpay', to='crm.gifttable24', verbose_name='gifttable'),
        ),
    ]
