# Generated by Django 4.2.1 on 2023-08-10 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0026_amountgiftpay_installment_gifttable24_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifttable24',
            name='user',
        ),
        migrations.CreateModel(
            name='TableGift3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifttable24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab3', to='crm.gifttable24', verbose_name='Gift Tables')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'TableGift3',
                'verbose_name_plural': 'TableGift3s',
            },
        ),
        migrations.CreateModel(
            name='TableGift2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifttable24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab2', to='crm.gifttable24', verbose_name='Gift Tables')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'TableGift2',
                'verbose_name_plural': 'TableGift2s',
            },
        ),
        migrations.CreateModel(
            name='TableGift1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifttable24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab1', to='crm.gifttable24', verbose_name='Gift Tables')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'TableGift1',
                'verbose_name_plural': 'TableGift1s',
            },
        ),
    ]
