# Generated by Django 4.2 on 2023-08-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_remove_gifttable24_user_tablegift3_tablegift2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablegift3',
            name='gifttable24',
        ),
        migrations.RemoveField(
            model_name='tablegift3',
            name='user',
        ),
        migrations.DeleteModel(
            name='TableGift2',
        ),
        migrations.DeleteModel(
            name='TableGift3',
        ),
    ]
