# Generated by Django 4.2 on 2023-08-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_remove_amountgiftpay_gifttable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablegift24',
            old_name='amounttab1',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='tablegift24',
            name='amounttab2',
        ),
        migrations.RemoveField(
            model_name='tablegift24',
            name='amounttab3',
        ),
    ]
