# Generated by Django 4.2 on 2023-08-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_rename_amounttab1_tablegift24_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablegift24',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
    ]
