# Generated by Django 4.2 on 2023-08-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_alter_tablegift24_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Table Name')),
                ('footer', models.CharField(blank=True, max_length=150, null=True, verbose_name='Footer')),
            ],
            options={
                'verbose_name': 'TableName',
                'verbose_name_plural': 'TableNames',
            },
        ),
        migrations.AlterField(
            model_name='tablegift24',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.tablename', verbose_name='Table Name'),
        ),
    ]
