# Generated by Django 4.2 on 2023-08-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_tablename_alter_tablegift24_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablegift24',
            old_name='name',
            new_name='tablename',
        ),
        migrations.AlterField(
            model_name='tablegift24',
            name='monthsequence',
            field=models.FloatField(verbose_name='Month Sequence'),
        ),
        migrations.AlterField(
            model_name='tablegift24',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
