# Generated by Django 4.2 on 2023-08-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_rename_name_tablegift24_tablename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablegift24',
            name='monthnumber',
            field=models.FloatField(verbose_name='Month Number'),
        ),
    ]
