# Generated by Django 4.2 on 2023-08-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_alter_tablegift24_monthnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='amountgiftpay',
        ),
        migrations.DeleteModel(
            name='AmountGiftPay',
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
