# Generated by Django 4.2 on 2023-08-13 14:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0037_remove_installment_amountgiftpay_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableGift',
            new_name='TableGiftUser',
        ),
    ]
