# Generated by Django 4.2 on 2023-08-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_rename_tablegift_tablegiftuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableGift24',
            new_name='TableGift',
        ),
        migrations.AlterModelOptions(
            name='tablegift',
            options={'verbose_name': 'TableGift', 'verbose_name_plural': 'TableGifts'},
        ),
    ]
