# Generated by Django 4.2 on 2023-08-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_rename_tablegift24_tablegift_alter_tablegift_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablegift',
            name='tablename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabgift', to='crm.tablename', verbose_name='Table Name'),
        ),
        migrations.DeleteModel(
            name='TableGiftUser',
        ),
    ]
