# Generated by Django 4.2 on 2023-08-13 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0040_alter_tablegift_tablename_delete_tablegiftuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableGiftUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablegift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabgiftuser', to='crm.tablegift', verbose_name='Gift Tables')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'TableGift',
                'verbose_name_plural': 'TableGifts',
            },
        ),
    ]
