# Generated by Django 4.2 on 2023-08-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_tableamount_installment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Installment',
            new_name='TableInstallment',
        ),
        migrations.AlterModelOptions(
            name='tablegiftuser',
            options={'verbose_name': 'TableGiftUser', 'verbose_name_plural': 'TableGiftUsers'},
        ),
        migrations.AlterModelOptions(
            name='tableinstallment',
            options={'verbose_name': 'TableInstallment', 'verbose_name_plural': 'TableInstallments'},
        ),
    ]
