# Generated by Django 4.2 on 2023-08-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_rename_installment_tableinstallment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableinstallment',
            name='payment',
            field=models.FloatField(default=1, verbose_name='Payment'),
            preserve_default=False,
        ),
    ]
