# Generated by Django 4.2.1 on 2023-08-16 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_tablegift_paytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablegift',
            name='gifts',
            field=models.CharField(max_length=200, verbose_name='Title Gifts'),
        ),
        migrations.AlterField(
            model_name='tableinstallment',
            name='tableamount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qst', to='crm.tablegiftuser', verbose_name='TableAmount'),
        ),
    ]
