# Generated by Django 4.1.3 on 2023-08-16 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_alter_tablegift_gifts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableamount',
            name='payment',
            field=models.FloatField(default=0, verbose_name='Payment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tableamount',
            name='tablegiftuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='crm.tablegiftuser', verbose_name='Table Gift'),
        ),
    ]
