# Generated by Django 4.1.3 on 2023-08-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_tableamount_payment_alter_tableamount_tablegiftuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableInstallment',
        ),
    ]
