# Generated by Django 4.1.3 on 2023-08-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_delete_tableinstallment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableamount',
            old_name='tablegiftuser',
            new_name='tabgiftusr',
        ),
    ]
