# Generated by Django 4.1.3 on 2023-08-16 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_rename_tablegiftuser_tableamount_tabgiftusr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablegiftuser',
            name='tablegift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabgiftusr', to='crm.tablegift', verbose_name='Gift Tables'),
        ),
    ]
