# Generated by Django 4.1.3 on 2023-08-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_alter_tableamount_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableAmount',
        ),
    ]
