# Generated by Django 4.1.3 on 2023-08-16 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_delete_tableamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('payment', models.FloatField(verbose_name='Payment')),
                ('tabgiftusr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='crm.tablegiftuser', verbose_name='Table Gift')),
            ],
            options={
                'verbose_name': 'TablePayment',
                'verbose_name_plural': 'TablePayments',
            },
        ),
    ]
