# Generated by Django 4.1.3 on 2023-08-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_tablegiftuser_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablegiftuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='tablegiftuser',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
