# Generated by Django 4.1.3 on 2023-08-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0061_tablegiftuser_active_tablegiftuser_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablegiftuser',
            name='countpay',
            field=models.IntegerField(default=1, verbose_name='Count Pay'),
        ),
    ]
