# Generated by Django 4.1.3 on 2023-08-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_tablegiftuser_countpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablegiftuser',
            name='countpay',
            field=models.IntegerField(verbose_name='Count Pay'),
        ),
    ]
