# Generated by Django 4.1.3 on 2023-08-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_alter_tablegiftuser_countpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepayment',
            name='tabgiftusr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='crm.tablegiftuser', verbose_name='Table Gift'),
        ),
    ]
