# Generated by Django 4.2 on 2023-08-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_alter_tablegiftuser_countchances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winnerlottery60',
            name='common',
        ),
        migrations.RemoveField(
            model_name='winnerlottery60',
            name='lottery',
        ),
        migrations.RemoveField(
            model_name='common60',
            name='lottery',
        ),
        migrations.DeleteModel(
            name='Lottery',
        ),
        migrations.DeleteModel(
            name='WinnerLottery60',
        ),
    ]
