# Generated by Django 4.2 on 2023-08-26 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_remove_winnerlottery60_common_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryC60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('quran', 'Quran memorization lottery'), ('ziarat', 'Visiting religious places')], max_length=200, null=True, verbose_name='Lottery')),
            ],
            options={
                'verbose_name': 'LotteryC60',
                'verbose_name_plural': 'LotteryC60s',
            },
        ),
        migrations.CreateModel(
            name='WinnerLottery60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('windate', models.DateTimeField(auto_now=True, verbose_name='Add Time')),
                ('common', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winquran', to='crm.common60')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winlottery', to='crm.lotteryc60')),
            ],
            options={
                'verbose_name': 'WinnerLottery60',
                'verbose_name_plural': 'WinnerLottery60s',
            },
        ),
        migrations.AddField(
            model_name='common60',
            name='lottery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lottery_c60', to='crm.lotteryc60', verbose_name='lottery'),
        ),
    ]
