# Generated by Django 4.2 on 2023-08-27 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_commonsamount_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonsamount',
            name='createdt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commonsamount',
            name='updatedt',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
    ]
