# Generated by Django 4.2 on 2023-08-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0074_commonsamount_createdt_commonsamount_updatedt'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicassistance',
            name='useramount',
            field=models.FloatField(default=1, verbose_name='User Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='common70',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='Pay Status'),
        ),
        migrations.AlterField(
            model_name='commondead',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='Pay Status'),
        ),
        migrations.AlterField(
            model_name='doingdead',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='Pay Status'),
        ),
        migrations.AlterField(
            model_name='judiciarydead',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='Pay Status'),
        ),
        migrations.AlterField(
            model_name='publicassistance',
            name='paystatus',
            field=models.BooleanField(default=False, verbose_name='Pay Status'),
        ),
    ]
