# Generated by Django 4.1.3 on 2024-01-07 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0075_publicassistance_useramount_alter_common70_paystatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'Postimg',
                'verbose_name_plural': 'Postimgs',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Storys',
            },
        ),
        migrations.CreateModel(
            name='ViewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('caption', models.TextField(verbose_name='Caption')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('postimg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewpost', to='crm.postimg')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewsory', to='crm.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StoryView',
                'verbose_name_plural': 'StoryViews',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('postimg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likepost', to='crm.postimg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
    ]
