# Generated by Django 4.1.3 on 2024-01-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_postmedia_story_viewstory_viewpost_likepost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewstory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='viewstory',
            name='story',
        ),
        migrations.RemoveField(
            model_name='viewstory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='ViewStory',
        ),
    ]
