# Generated by Django 4.1.3 on 2024-01-08 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0077_alter_viewstory_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostMedia',
            new_name='SocialMedia',
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Media'},
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='postmedia',
            new_name='socialmedia',
        ),
        migrations.RenameField(
            model_name='viewpost',
            old_name='postmedia',
            new_name='socialmedia',
        ),
        migrations.AlterUniqueTogether(
            name='viewpost',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='viewpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('user', 'socialmedia')},
        ),
        migrations.AlterUniqueTogether(
            name='viewpost',
            unique_together={('user', 'socialmedia')},
        ),
    ]
