# Generated by Django 4.1.3 on 2024-01-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0078_rename_postmedia_socialmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='mediatype',
            field=models.CharField(choices=[('post', 'Post'), ('story', 'Story')], default=0, max_length=5, verbose_name='Media Type'),
            preserve_default=False,
        ),
    ]
