# Generated by Django 4.1.3 on 2024-01-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0079_socialmedia_mediatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='adv',
            field=models.BooleanField(default=False, verbose_name='Advertising'),
        ),
    ]
