# Generated by Django 4.1.3 on 2024-01-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0080_socialmedia_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='mediatype',
            field=models.CharField(choices=[('post', 'Post'), ('story', 'Story')], default=0, max_length=5, verbose_name='Media Type'),
        ),
    ]
