# Generated by Django 4.1.3 on 2024-01-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0084_newstext_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
