# Generated by Django 4.1.3 on 2024-01-10 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0085_commentpost_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='createdt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentpost',
            name='updatedt',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='updatedate',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
    ]
