# Generated by Django 4.1.3 on 2024-01-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0086_commentpost_createdt_commentpost_updatedt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
