# Generated by Django 4.1.3 on 2024-01-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0087_socialmedia_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common60',
            name='sickness',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='sickness'),
        ),
        migrations.AlterField(
            model_name='common61',
            name='sickness',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='sickness'),
        ),
        migrations.AlterField(
            model_name='common70',
            name='sickness',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='sickness'),
        ),
    ]
