# Generated by Django 4.1.3 on 2024-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0088_alter_common60_sickness_alter_common61_sickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='force',
            field=models.BooleanField(default=False, verbose_name='Force Notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='URL'),
        ),
    ]
