# Generated by Django 4.1.3 on 2024-01-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0089_notification_force_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='see',
            field=models.JSONField(blank=True, default={}, null=True, verbose_name='See'),
        ),
    ]
