services:
  backendcrmdev:
    build:
      context: ../../
      dockerfile: docker/dockerfiles/dev.Dockerfile
    image: crmmngmnt:dev
    pull_policy: never
    container_name: CRM_dev
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ../../backend:/app
    ports:
      - "127.0.0.1:8001:8001" # Only accessible from server itself
    environment:
      - DEBUG=True
    command: >
      sh -c "
      if [ ! -f .env ]; then
        cp .env.example .env;
      fi &&
      python manage.py runserver 0.0.0.0:8001
      "
